Embedded Systems Library: C:/SE/SE1819/src/flash.c File Reference
flash.c File Reference
#include "flash.h"
#include "LPC17xx.h"
#include "string.h"
Macros
#define IAP_LOCATION 0x1FFF1FF1
#define SMALL_SECTOR_SIZE 0x1000
#define BIG_SECTOR_SIZE 0x8000
#define START_BIG_ADDRESS 0x00010000
#define END_BIG_ADDRESS 0x0007FFFF
#define NUMBER_SMALL_SECTORS 16
#define CHUNK_SIZE 256
#define PREPARE_SECTOR_COMMAND 50
#define COPY_COMMAND 51
#define ERASE_SECTOR_COMMAND 52
#define COMPARE_COMMAND 56
#define CMD_SUCCESS 0
#define BUSY 11
#define INVALID_SECTOR 7
Typedefs
typedef void(* IAP) (unsigned int [], unsigned int[])
Functions
unsigned int ExecuteIAP (unsigned int *commandTable, unsigned int *outputTable)
void GetSectors (unsigned int dstAddr, unsigned int size, unsigned int *startSector, unsigned int *endSector)
unsigned int PrepareSector (unsigned int startSector, unsigned int endSector)
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Erases the content of Flash sectors from startSector to endSector, returning the status code.
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Writes a data block to the Flash memory, returning the status code.
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Compares a Flash memory data block, returning the status code.
Macro Definition Documentation
BIG_SECTOR_SIZE
#define BIG_SECTOR_SIZE 0x8000
Definition at line 15 of file flash.c.
Referenced by GetSectors().
BUSY
#define BUSY 11
Definition at line 27 of file flash.c.
CHUNK_SIZE
#define CHUNK_SIZE 256
Definition at line 19 of file flash.c.
Referenced by FLASH_WriteData().
CMD_SUCCESS
#define CMD_SUCCESS 0
Definition at line 26 of file flash.c.
Referenced by FLASH_EraseSectors(), and FLASH_WriteData().
COMPARE_COMMAND
#define COMPARE_COMMAND 56
Definition at line 24 of file flash.c.
Referenced by FLASH_VerifyData().
COPY_COMMAND
#define COPY_COMMAND 51
Definition at line 22 of file flash.c.
Referenced by FLASH_WriteData().
END_BIG_ADDRESS
#define END_BIG_ADDRESS 0x0007FFFF
Definition at line 17 of file flash.c.
ERASE_SECTOR_COMMAND
#define ERASE_SECTOR_COMMAND 52
Definition at line 23 of file flash.c.
Referenced by FLASH_EraseSectors().
IAP_LOCATION
#define IAP_LOCATION 0x1FFF1FF1
Definition at line 12 of file flash.c.
Referenced by ExecuteIAP().
INVALID_SECTOR
#define INVALID_SECTOR 7
Definition at line 28 of file flash.c.
NUMBER_SMALL_SECTORS
#define NUMBER_SMALL_SECTORS 16
Definition at line 18 of file flash.c.
Referenced by GetSectors().
PREPARE_SECTOR_COMMAND
#define PREPARE_SECTOR_COMMAND 50
Definition at line 21 of file flash.c.
Referenced by PrepareSector().
SMALL_SECTOR_SIZE
#define SMALL_SECTOR_SIZE 0x1000
Definition at line 14 of file flash.c.
Referenced by GetSectors().
START_BIG_ADDRESS
#define START_BIG_ADDRESS 0x00010000
Definition at line 16 of file flash.c.
Referenced by GetSectors().
Typedef Documentation
IAP
typedef void(* IAP) (unsigned int [], unsigned int[])
Definition at line 31 of file flash.c.
Function Documentation
ExecuteIAP()
unsigned int ExecuteIAP (unsigned int * commandTable, unsigned int * outputTable)
Definition at line 34 of file flash.c.
References IAP_LOCATION.
Referenced by FLASH_EraseSectors(), FLASH_VerifyData(), and PrepareSector().
GetSectors()
void GetSectors (unsigned int dstAddr, unsigned int size, unsigned int * startSector, unsigned int * endSector)
Definition at line 42 of file flash.c.
References BIG_SECTOR_SIZE, NUMBER_SMALL_SECTORS, SMALL_SECTOR_SIZE, and START_BIG_ADDRESS.
Referenced by FLASH_WriteData().
PrepareSector()
unsigned int PrepareSector (unsigned int startSector, unsigned int endSector)
Definition at line 59 of file flash.c.
References ExecuteIAP(), and PREPARE_SECTOR_COMMAND.
Referenced by FLASH_EraseSectors(), and FLASH_WriteData().