Embedded Systems Library: UART Public Functions
UART Public Functions
UART
Macros
#define UART_PORT 0
Functions
void ResetBuffers ()
Resets the UART transmit and receive buffers.
void UART_Init (unsigned int baudrate)
Initializes the UART controller, configures the respective pins and sets the baudrate.
bool UART_Send (unsigned char *buffer, unsigned int size)
Sends data using UART. Returns true if successful or false if not successful.
bool UART_Recieve (unsigned char *buffer, unsigned int size, bool waitOK)
Receives data through UART. Returns true if successful or false if not successful.
Detailed Description
Macro Definition Documentation
UART_PORT
#define UART_PORT 0
Definition at line 24 of file uart.h.
Function Documentation
ResetBuffers()
void ResetBuffers ()
Resets the UART transmit and receive buffers.
Returns
void.
Definition at line 35 of file uart.c.
References RB_Reset().
Referenced by WIFI_Init().
UART_Init()
void UART_Init (unsigned int baudrate)
Initializes the UART controller, configures the respective pins and sets the baudrate.
Parameters
baudrate baudrate to be defined.
Returns
Void.
Definition at line 73 of file uart.c.
References GetUartDL(), PCLK_VAL, UART0_PCLK_BIT, UART0_PCON_BIT, UART0_PINSEL_MASK, and UART0_PINSEL_VAL.
Referenced by WIFI_Init().
UART_Recieve()
bool UART_Recieve (unsigned char * buffer, unsigned int size, bool waitOK)
Receives data through UART. Returns true if successful or false if not successful.
Parameters
buffer Pointer to position of memory where received bytes will be stored.
size Number of bytes to receive.
waitOK Determines if an "OK" is expected at the end of the packet.
Returns
bool.
Definition at line 113 of file uart.c.
UART_Send()
bool UART_Send (unsigned char * buffer, unsigned int size)
Sends data using UART. Returns true if successful or false if not successful.
Parameters
buffer Pointer to array of bytes to be transfered.
size Number of bytes to be transfered.
Returns
bool.
Definition at line 92 of file uart.c.