Embedded Systems Library: LED Public Functions
LED Public Functions
LED
Functions
void LED_Init (int portId, int pinId, int state)
Initializes the LED API.
int LED_GetState (void)
Get LED state.
void LED_On (void)
Turn LED on.
void LED_Off (void)
Turn LED off.
Detailed Description
Function Documentation
LED_GetState()
int LED_GetState (void)
Get LED state.
Returns
status of LED. The 0 indicate led is off and 1 LED is on.
Definition at line 29 of file led.c.
References gpio, and pinMask.
LED_Init()
void LED_Init (int portId, int pinId, int state)
Initializes the LED API.
Parameters
portId : GPIO port associated to the LED.
pinId : Index of pin in which the LED is located.
state : State of the LED. The 0 indicate led off and 1 LED on.
Returns
Void
Note
This function must be called prior to any other LED functions. The LED will start in the value passed in the parameter.
Definition at line 17 of file led.c.
References gpio, GPIO_PORT_DISTANCE, LED_Off(), LED_On(), and pinMask.
LED_Off()
void LED_Off (void)
Turn LED off.
Returns
Nothing
Definition at line 37 of file led.c.
References gpio, and pinMask.
Referenced by LED_Init().
LED_On()
void LED_On (void)
Turn LED on.
Returns
Nothing
Definition at line 33 of file led.c.
References gpio, and pinMask.
Referenced by LED_Init().