Embedded Systems Library: Waitos Public Functions
Waitos Public Functions
Waitos
Functions
void WAITOS_Ms (unsigned int millis)
Waits a number of milliseconds.
Detailed Description
Function Documentation
WAITOS_Ms()
void WAITOS_Ms (unsigned int millis)
Waits a number of milliseconds.
Parameters
millis the whole number of milliseconds to wait.
Definition at line 13 of file waitos.c.
Referenced by KEYPADOS_PoolKeypad(), LCDOS_Init(), MFRC522_WaitMs(), and WIFI_Init().