Embedded Systems Library: RB Public Functions
RB Public Functions
RB
Data Structures
struct ringbuffer
Macros
#define RB_BUFFER_SIZE 256
Typedefs
typedef struct ringbuffer RINGBUFF_DSC
Functions
void RB_Reset (RINGBUFF_DSC *buffer)
Resets the buffer.
bool RB_Full (RINGBUFF_DSC *buffer)
Returns true if the buffer is full and false otherwise.
bool RB_Empty (RINGBUFF_DSC *buffer)
Returns true if the buffer is empty and false otherwise.
void RB_Push (RINGBUFF_DSC *buffer, unsigned char val)
Pushes a value into a buffer.
unsigned char RB_Pop (RINGBUFF_DSC *buffer)
Pops a value from a buffer and returns that value.
Detailed Description
Macro Definition Documentation
RB_BUFFER_SIZE
#define RB_BUFFER_SIZE 256
Definition at line 23 of file rb.h.
Typedef Documentation
RINGBUFF_DSC
typedef struct ringbuffer RINGBUFF_DSC
Function Documentation
RB_Empty()
bool RB_Empty (RINGBUFF_DSC * buffer)
Returns true if the buffer is empty and false otherwise.
Parameters
buffer the buffer to be checked.
Returns
bool.
Definition at line 21 of file rb.c.
References ringbuffer::full, ringbuffer::get, and ringbuffer::put.
Referenced by UART0_IRQHandler().
RB_Full()
bool RB_Full (RINGBUFF_DSC * buffer)
Returns true if the buffer is full and false otherwise.
Parameters
buffer the buffer to be checked.
Returns
bool.
Definition at line 16 of file rb.c.
References ringbuffer::full.
Referenced by UART0_IRQHandler().
RB_Pop()
unsigned char RB_Pop (RINGBUFF_DSC * buffer)
Pops a value from a buffer and returns that value.
Parameters
buffer the buffer to pop the value.
Returns
unsigned char.
Definition at line 31 of file rb.c.
References ringbuffer::buffer, ringbuffer::full, and ringbuffer::get.
RB_Push()
void RB_Push (RINGBUFF_DSC * buffer, unsigned char val)
Pushes a value into a buffer.
Parameters
buffer the buffer to push the value.
val the value to be pushed
Returns
void.
Definition at line 25 of file rb.c.
References ringbuffer::buffer, ringbuffer::full, ringbuffer::get, and ringbuffer::put.
Referenced by UART0_IRQHandler().
RB_Reset()
void RB_Reset (RINGBUFF_DSC * buffer)
Resets the buffer.
Parameters
buffer the buffer to be reset.
Returns
void.
Definition at line 10 of file rb.c.
Referenced by ResetBuffers().