Embedded Systems Library: Wifi Public Functions
Wifi Public Functions
Wifi
Functions
void WIFI_Init ()
Initializes the UART controller with a supported frequency, to be the communication protocol used, and configures the pins used.
bool WIFI_Cmd (unsigned char *cmd, unsigned char *response, unsigned int *length, bool waitOK)
Sends a command and waits for the response. Returns true if successful or false if not successful.
bool WIFI_Data (unsigned char *data, unsigned int size, unsigned char *response, unsigned int *length, bool waitOK)
Sends data and waits for the response. Returns true if successful or false if not successful.
Detailed Description
Function Documentation
WIFI_Cmd()
bool WIFI_Cmd (unsigned char * cmd, unsigned char * response, unsigned int * length, bool waitOK)
Sends a command and waits for the response. Returns true if successful or false if not successful.
Parameters
cmd Pointer to array of bytes that make up the command to send.
response Pointer to position in memory where the response is going to be written.
length Pointer to a variable where the length of the response is going to be written.
waitOK Determines if an "OK" is expected at the end of the response.
Returns
bool.
Definition at line 41 of file wifi.c.
References CR_LF_SIZE.
WIFI_Data()
bool WIFI_Data (unsigned char * data, unsigned int size, unsigned char * response, unsigned int * length, bool waitOK)
Sends data and waits for the response. Returns true if successful or false if not successful.
Parameters
data Pointer to array of bytes that make up the data to send.
size Amount of bytes of data to send.
response Pointer to position in memory where the response is going to be written.
length Pointer to a variable where the length of the response is going to be written.
waitOK Determines if an "OK" is expected at the end of the response.
Returns
bool.
Definition at line 64 of file wifi.c.
WIFI_Init()
void WIFI_Init ()
Initializes the UART controller with a supported frequency, to be the communication protocol used, and configures the pins used.
Returns
Void.
Definition at line 22 of file wifi.c.
References GPIO_RST_PIN, ResetBuffers(), UART_BAUD, UART_Init(), and WAITOS_Ms().
Referenced by ESP_Init().