Embedded Systems Library: FLASH Public Functions
FLASH Public Functions
FLASH
Functions
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Erases the content of Flash sectors from startSector to endSector, returning the status code.
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Writes a data block to the Flash memory, returning the status code.
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Compares a Flash memory data block, returning the status code.
Detailed Description
Function Documentation
FLASH_EraseSectors()
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Erases the content of Flash sectors from startSector to endSector, returning the status code.
Parameters
startSector initial sector to erase.
endSector last sector to erase.
Returns
unsigned int.
Definition at line 65 of file flash.c.
References CMD_SUCCESS, ERASE_SECTOR_COMMAND, ExecuteIAP(), and PrepareSector().
FLASH_VerifyData()
unsigned int FLASH_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Compares a Flash memory data block, returning the status code.
Parameters
dstAddr reference to the destination address.
srcAddr reference to the source address.
size number of bytes to compare.
Returns
unsigned int.
Definition at line 110 of file flash.c.
References COMPARE_COMMAND, and ExecuteIAP().
FLASH_WriteData()
unsigned int FLASH_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Writes a data block to the Flash memory, returning the status code.
Parameters
dstAddr reference to the destination address.
srcAddr reference to the source address.
size number of bytes to write.
Returns
unsigned int.
Definition at line 78 of file flash.c.
References CHUNK_SIZE, CMD_SUCCESS, COPY_COMMAND, GetSectors(), and PrepareSector().