Embedded Systems Library: Keypados Public Functions
Keypados Public Functions
Keypados
Macros
#define NUMBER_OF_LINES 4
#define NUMBER_OF_COLUMNS 3
#define KEY_COMBINATION_UNSUPPORTED_CODE -1
#define COMBINATION_CODE 127
Functions
void KEYPADOS_Init (int layout[12], QueueHandle_t queue, SemaphoreHandle_t smphr)
Initializes the system to allow access to the peripheral. As such, receives in the parameters the vector with the codes of the 12 keys (layout), and the OS objects that will be used to communicate between tasks.
void KEYPADOS_ProcessKey ()
Waits for a key press, processes the key pressed and pushes it to the queue. to be used by the keypad task.
int KEYPADOS_PoolKeypad ()
Pools keypad to determine which key was pressed and returns that key code.
int KEYPADOS_GetKey (TickType_t ticks)
Returns the first key in the queue.
Detailed Description
Macro Definition Documentation
COMBINATION_CODE
#define COMBINATION_CODE 127
Definition at line 43 of file keypados.h.
KEY_COMBINATION_UNSUPPORTED_CODE
#define KEY_COMBINATION_UNSUPPORTED_CODE -1
This keypad does NOT support any key combination (keys pressed at the same time) of two keys in DIFFERENT LINES, the key pressed in the uppermost row will PROBABLLY be the one recorded (not guaranteed).
This keypad only supports a single key combination that returns COMBINATION_CODE all other combinations tried in the same line will return KEY_COMBINATION_UNSUPPORTED_CODE
Definition at line 42 of file keypados.h.
NUMBER_OF_COLUMNS
#define NUMBER_OF_COLUMNS 3
Definition at line 33 of file keypados.h.
NUMBER_OF_LINES
#define NUMBER_OF_LINES 4
Number of lines and columns in the keypad
Definition at line 32 of file keypados.h.
Function Documentation
KEYPADOS_GetKey()
int KEYPADOS_GetKey (TickType_t ticks)
Returns the first key in the queue.
Parameters
ticks number of ticks to wait for a key.
Returns
int
Definition at line 96 of file keypados.c.
KEYPADOS_Init()
void KEYPADOS_Init (int layout[12], QueueHandle_t queue, SemaphoreHandle_t smphr)
Initializes the system to allow access to the peripheral. As such, receives in the parameters the vector with the codes of the 12 keys (layout), and the OS objects that will be used to communicate between tasks.
Parameters
layout array with the keys' codes
queue queue object that holds the keys pressed so different tasks can fetch
smphr semaphore object that wakes thread that will process keys when a key is pressed
Returns
Void
Definition at line 47 of file keypados.c.
References BITS_TO_PINMODE, INPUT_MASK, Layout, LAYOUT_SIZE, OUTPUT_MASK, queue, and Semaphore.
KEYPADOS_PoolKeypad()
int KEYPADOS_PoolKeypad ()
Pools keypad to determine which key was pressed and returns that key code.
Returns
int
Definition at line 70 of file keypados.c.
References COMBINATION_CODE, INPUT_MASK, KEY_COMBINATION_UNSUPPORTED_CODE, Layout, NUMBER_OF_COLUMNS, NUMBER_OF_LINES, OUTPUT_MASK, SHIFT_TO_INPUT, SHIFT_TO_OUTPUT, VAL_TO_XOR, and WAITOS_Ms().
Referenced by KEYPADOS_ProcessKey().
KEYPADOS_ProcessKey()
void KEYPADOS_ProcessKey ()
Waits for a key press, processes the key pressed and pushes it to the queue. to be used by the keypad task.
Returns
void
Definition at line 61 of file keypados.c.
References KEYPADOS_PoolKeypad(), and Semaphore.