Embedded Systems Library: SPI Public Functions
SPI Public Functions
SPI
Functions
void SPI_Init (void)
Initializes the SPI controller and configures the respective pins.
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Configures the SPI transmit frequency, number of data bits and mode.
void SPI_BeginTransfer (int csBitId)
Sets the slave's chip select to active.
void SPI_EndTransfer (int csBitId)
Sets the slave's chip select to inactive.
void SPI_Transfer (unsigned short *txBuffer, unsigned short *rxBuffer, int length)
Performs a transfer.
Detailed Description
Function Documentation
SPI_BeginTransfer()
void SPI_BeginTransfer (int csBitId)
Sets the slave's chip select to active.
Parameters
csBitId slave's cs bit.
Returns
Void.
Definition at line 67 of file spi.c.
Referenced by MFRC522_Select().
SPI_ConfigTransfer()
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Configures the SPI transmit frequency, number of data bits and mode.
Parameters
frequency the frequency on which the spi will send or recieve data.
bitData number of data bits.
mode mode in which the spi will operate (CPOL, CPHA).
Returns
Void.
Definition at line 43 of file spi.c.
Referenced by MFRC522_PreInit().
SPI_EndTransfer()
void SPI_EndTransfer (int csBitId)
Sets the slave's chip select to inactive.
Parameters
csBitId slave's cs bit.
Returns
Void.
Definition at line 71 of file spi.c.
Referenced by MFRC522_Select().
SPI_Init()
void SPI_Init (void)
Initializes the SPI controller and configures the respective pins.
Returns
Void.
Definition at line 27 of file spi.c.
References BIT_IN_PCONP, MASK_IN_PCLKSEL1, MASK_IN_PINSEL0, MASK_IN_PINSEL1, VALUE_TO_PINSEL0, and VALUE_TO_PINSEL1.
Referenced by MFRC522_PreInit().
SPI_Transfer()
void SPI_Transfer (unsigned short * txBuffer, unsigned short * rxBuffer, int length)
Performs a transfer.
Parameters
txBuffer buffer to transmit data.
rxBuffer buffer to receive data.
length number of data chunks to be transfered.
Returns
Void.
Definition at line 75 of file spi.c.
References BSY_BIT.
Referenced by MFRC522_Transfer().