Embedded Systems Library: LCDText Public Functions
LCDText Public Functions
LCDText
Functions
void LCDText_Init (void)
Initializes the system to allow access to the peripheral using 2 lines, 16 columns and 4bit communication.
void LCDText_WriteChar (char ch)
Writes a character in the actual cursor position.
void LCDText_WriteString (char *str)
Writes a string in the actual cursor position.
void LCDText_Locate (unsigned int row, unsigned int column)
Positions the cursor in the line row and column column.
void LCDText_Clear (void)
Clears the display.
void LCDText_Printf (char *fmt,...)
Writes the formated string fmt to the display.
Detailed Description
Function Documentation
LCDText_Clear()
void LCDText_Clear (void)
Clears the display.
Returns
Void
Definition at line 96 of file lcd.c.
LCDText_Init()
void LCDText_Init (void)
Initializes the system to allow access to the peripheral using 2 lines, 16 columns and 4bit communication.
Returns
Void
Definition at line 49 of file lcd.c.
References WAIT_Ms(), and WriteHalf().
LCDText_Locate()
void LCDText_Locate (unsigned int row, unsigned int column)
Positions the cursor in the line row and column column.
Parameters
row row selected
column column selected
Returns
Void
Definition at line 78 of file lcd.c.
References LINE_0_START_ADDRESS, and LINE_1_START_ADDRESS.
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Writes the formated string fmt to the display.
Parameters
fmt formated string
... arguments for the format
Returns
Void
Definition at line 100 of file lcd.c.
References LCDText_WriteString().
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes a character in the actual cursor position.
Parameters
ch character to write
Returns
Void
Definition at line 66 of file lcd.c.
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes a string in the actual cursor position.
Parameters
str string to write
Returns
Void
Definition at line 70 of file lcd.c.
Referenced by LCDText_Printf().