Embedded Systems Library: MFRC Public Functions
MFRC Public Functions
MFRC
Functions
void MFRC522_PreInit (void)
Runs necessary initializations for the library.
void MFRC522_Reset (bool assert)
Handles the reset pin of RC522 according to the assert parameter.
void MFRC522_Select (bool assert)
Handles the chip select pin of RC522 according to the assert parameter.
uint8_t MFRC522_Transfer (uint8_t value)
Performs the transmission/reception of a byte returning the received byte.
void MFRC522_WaitMs (uint32_t millis)
Waits the value of the millis param in milliseconds.
Detailed Description
Function Documentation
MFRC522_PreInit()
void MFRC522_PreInit (void)
Runs necessary initializations for the library.
Returns
Void.
Definition at line 26 of file mfrc.c.
References CS_BIT, GPIO_INPUT_PINMODE0_BITS, GPIO_PINSEL0_BITS, GPIO_PINSEL1_BITS, IRQ_BIT, RST_BIT, SPI_ConfigTransfer(), SPI_Init(), TRANSF_BIT_SIZE, TRANSF_FREQ, and TRANSF_MODE.
MFRC522_Reset()
void MFRC522_Reset (bool assert)
Handles the reset pin of RC522 according to the assert parameter.
Parameters
assert boolean that defines if reset is to be set.
Returns
Void.
Definition at line 38 of file mfrc.c.
References RST_BIT.
MFRC522_Select()
void MFRC522_Select (bool assert)
Handles the chip select pin of RC522 according to the assert parameter.
Parameters
assert boolean that defines if CS is to be set.
Returns
Void.
Definition at line 48 of file mfrc.c.
References CS_BIT, SPI_BeginTransfer(), and SPI_EndTransfer().
MFRC522_Transfer()
uint8_t MFRC522_Transfer (uint8_t value)
Performs the transmission/reception of a byte returning the received byte.
Parameters
value byte to be transfered.
Returns
uint8_t.
Definition at line 58 of file mfrc.c.
References SPI_Transfer().
MFRC522_WaitMs()
void MFRC522_WaitMs (uint32_t millis)
Waits the value of the millis param in milliseconds.
Parameters
millis number of milliseconds to wait.
Returns
Void.
Definition at line 66 of file mfrc.c.
References WAITOS_Ms().