Embedded Systems Library: LCDos Public Functions
LCDos Public Functions
LCDos
Macros
#define ILLEGAL_ROW -2
#define ILLEGAL_COL -3
#define CMD_SIZE 33
Functions
void LCDOS_Init (QueueHandle_t queue)
Initializes the system to allow access to the peripheral using 2 lines, 16 columns and 4bit communication.
void LCDOS_ProcessCmd ()
Waits for queued commands and sends them to the display.
int LCDOS_Locate (unsigned int row, unsigned int column)
Queues command that positions the cursor in the line row and column column. Returns 1 if successfully queued and 0 otherwise.
int LCDOS_Clear (void)
Queues command that clears the display. Returns 1 if successfully queued and 0 otherwise.
int LCDOS_Printf (char *fmt,...)
Queues command that writes the formated string fmt to the display. Returns 1 if successfully queued and 0 otherwise.
Detailed Description
Macro Definition Documentation
CMD_SIZE
#define CMD_SIZE 33
Definition at line 29 of file lcdos.h.
Referenced by LCDOS_ProcessCmd().
ILLEGAL_COL
#define ILLEGAL_COL -3
Definition at line 28 of file lcdos.h.
Referenced by LCDOS_Locate().
ILLEGAL_ROW
#define ILLEGAL_ROW -2
Definition at line 27 of file lcdos.h.
Referenced by LCDOS_Locate().
Function Documentation
LCDOS_Clear()
int LCDOS_Clear (void)
Queues command that clears the display. Returns 1 if successfully queued and 0 otherwise.
Returns
int
Definition at line 144 of file lcdos.c.
References QueueLcd.
LCDOS_Init()
void LCDOS_Init (QueueHandle_t queue)
Initializes the system to allow access to the peripheral using 2 lines, 16 columns and 4bit communication.
Parameters
queue queue object that will hold commands to be send by the lcd task to the display.
Returns
Void
Definition at line 93 of file lcdos.c.
References queue, QueueLcd, WAITOS_Ms(), and WriteHalf().
LCDOS_Locate()
int LCDOS_Locate (unsigned int row, unsigned int column)
Queues command that positions the cursor in the line row and column column. Returns 1 if successfully queued and 0 otherwise.
Parameters
row row selected
column column selected
Returns
int
Definition at line 129 of file lcdos.c.
References ILLEGAL_COL, ILLEGAL_ROW, and QueueLcd.
LCDOS_Printf()
int LCDOS_Printf (char * fmt, ...)
Queues command that writes the formated string fmt to the display. Returns 1 if successfully queued and 0 otherwise.
Parameters
fmt formated string
... arguments for the format
Returns
Void
Definition at line 153 of file lcdos.c.
References QueueLcd.
LCDOS_ProcessCmd()
void LCDOS_ProcessCmd ()
Waits for queued commands and sends them to the display.
Returns
void
Definition at line 110 of file lcdos.c.
References Clear(), CMD_SIZE, Locate(), Print(), and QueueLcd.