Embedded Systems Library: C:/SE/SE1819/src/lcdos.c File Reference
lcdos.c File Reference
#include "lcdos.h"
#include "waitos.h"
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
Macros
#define LINE_0_START_ADDRESS 0x00
#define LINE_1_START_ADDRESS 0x40
#define CLEAR_DISPLAY_COMMAND 0x01
#define LINE_LENGTH 16
Functions
void WriteHalf (unsigned int bits, unsigned int rs)
void WriteChar (char ch)
void WriteString (char *str)
void Locate (unsigned int row, unsigned int column)
void Clear ()
void Print (char *str)
void LCDOS_Init (QueueHandle_t queue)
Initializes the system to allow access to the peripheral using 2 lines, 16 columns and 4bit communication.
void LCDOS_ProcessCmd ()
Waits for queued commands and sends them to the display.
int LCDOS_Locate (unsigned int row, unsigned int column)
Queues command that positions the cursor in the line row and column column. Returns 1 if successfully queued and 0 otherwise.
int LCDOS_Clear (void)
Queues command that clears the display. Returns 1 if successfully queued and 0 otherwise.
int LCDOS_Printf (char *fmt,...)
Queues command that writes the formated string fmt to the display. Returns 1 if successfully queued and 0 otherwise.
Variables
QueueHandle_t QueueLcd
Macro Definition Documentation
CLEAR_DISPLAY_COMMAND
#define CLEAR_DISPLAY_COMMAND 0x01
Definition at line 16 of file lcdos.c.
LINE_0_START_ADDRESS
#define LINE_0_START_ADDRESS 0x00
Definition at line 14 of file lcdos.c.
Referenced by Locate().
LINE_1_START_ADDRESS
#define LINE_1_START_ADDRESS 0x40
Definition at line 15 of file lcdos.c.
Referenced by Locate().
LINE_LENGTH
#define LINE_LENGTH 16
Definition at line 17 of file lcdos.c.
Function Documentation
Clear()
void Clear ()
Definition at line 76 of file lcdos.c.
Referenced by LCDOS_ProcessCmd().
Locate()
void Locate (unsigned int row, unsigned int column)
Definition at line 64 of file lcdos.c.
References LINE_0_START_ADDRESS, and LINE_1_START_ADDRESS.
Referenced by LCDOS_ProcessCmd().
Print()
void Print (char * str)
Definition at line 80 of file lcdos.c.
Referenced by LCDOS_ProcessCmd().
WriteChar()
void WriteChar (char ch)
Definition at line 52 of file lcdos.c.
WriteHalf()
void WriteHalf (unsigned int bits, unsigned int rs)
Definition at line 21 of file lcdos.c.
Referenced by LCDOS_Init().
WriteString()
void WriteString (char * str)
Definition at line 56 of file lcdos.c.
Variable Documentation
QueueLcd
QueueHandle_t QueueLcd
Definition at line 19 of file lcdos.c.
Referenced by LCDOS_Clear(), LCDOS_Init(), LCDOS_Locate(), LCDOS_Printf(), and LCDOS_ProcessCmd().